name: Deploy to Server

on:
  push:
    branches: [ master ]
    paths:
      - '.vitepress/**'
      - 'docs/**'
      - '.github/workflows/deploy.yml'
      - 'public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build VitePress site
        run: |
          npm install
          npm run docs:build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
#          key: ${{ secrets.SERVER_SSH_KEY }}
          key: '-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACBPjqtlENZR6vzLtbV7niITpwRCZ607g+oYUSp6Ng20WQAAAJjZLsU62S7F
OgAAAAtzc2gtZWQyNTUxOQAAACBPjqtlENZR6vzLtbV7niITpwRCZ607g+oYUSp6Ng20WQ
AAAEDA+sUSQrQUhzuiqaJIef9phZeNPwuSTfA4/cBPZyNbmE+Oq2UQ1lHq/Mu1tXueIhOn
BEJnrTuD6hhRKno2DbRZAAAAFWdpdGh1Yi1hY3Rpb25zLWRlcGxveQ==
-----END OPENSSH PRIVATE KEY-----'
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SERVER_PORT }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts


      - name: Clear target directory
        run: ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "rm -rf ${{ secrets.DEPLOY_PATH }}/*"

      - name: Deploy with rsync
        run: rsync -avz -e "ssh -p ${{ secrets.SERVER_PORT }}" ./.vitepress/dist/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}